<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>sibarum.neuralchemy</groupId>
        <artifactId>na-parent</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>na-nn-visualizer</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>sibarum.neuralchemy</groupId>
            <artifactId>na-brnn</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>sibarum.neuralchemy</groupId>
            <artifactId>na-raylib</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.5.0</version>
                <configuration>
                    <mainClass>sibarum.neuralchemy.visualizer.BrnVisualizerMain</mainClass>
                    <executable>java</executable>
                    <arguments>
                        <argument>--enable-native-access=ALL-UNNAMED</argument>
                        <argument>-classpath</argument>
                        <classpath/>
                        <argument>sibarum.neuralchemy.visualizer.BrnVisualizerMain</argument>
                    </arguments>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
